### ISSUE TITLE
Error on running App

### ISSUE THREAD

**Issue by ketul93** [QuickDraw-sketchRecognition/Sketch_Recognition#2]
By running "python3 QuickDrawApp.py"

Output:- 

Using TensorFlow backend.
2020-08-01 15:37:43.510511: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-01 15:37:43.530886: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8cd7c305a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-01 15:37:43.530930: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
processed: (1, 80, 80, 1)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
Traceback (most recent call last):
  File "QuickDrawApp.py", line 144, in <module>
    main()
  File "QuickDrawApp.py", line 67, in main
    if len(blackboard_cnts) >= 1:
TypeError: object of type 'NoneType' has no len()

**Comment by ketul93** [comment]
> By running "python3 QuickDrawApp.py"
> 
> Output:-
> 
> Using TensorFlow backend.
> 2020-08-01 15:37:43.510511: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-08-01 15:37:43.530886: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8cd7c305a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-08-01 15:37:43.530930: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
> processed: (1, 80, 80, 1)
> 
> 0
> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9
> 10
> 11
> 12
> 13
> 14
> Traceback (most recent call last):
> File "QuickDrawApp.py", line 144, in
> main()
> File "QuickDrawApp.py", line 67, in main
> if len(blackboard_cnts) >= 1:
> TypeError: object of type 'NoneType' has no len()

Solved it with OpenCV version 3.4.10.35
